export const ADD_COUNT = "ADD_COUNT";
export const UPDATE_USERNAME_ENTRY = "UPDATE_USERNAME_ENTRY";
export const UPDATE_PASSWORD_ENTRY = "UPDATE_PASSWORD_ENTRY";
export const ATTEMPT_SIGN_IN = "ATTEMPT_SIGN_IN";
export const CHANGE_TRIP = "CHANGE_TRIP";